on:
  push:
    branches:
      - master
      - 15x
  pull_request:
    branches:
      - master
      - 15x
jobs:

  windows:
    name: windows Build
    runs-on: vs2017-win2016
    steps:
      - uses: actions/checkout@v2
      - run: |
         git submodule update --init
         git lfs install
         git lfs pull
        
      - name: Build
        run: python build.py
        shell: cmd

      - name: Test
        run: |
         cd build/Dev/Cpp/Test/Release/
         Test.exe ci
        shell: cmd

      - name: Upload Test
        uses: actions/upload-artifact@v1
        with:
          name: Test
          path: build/Dev/Cpp/Test/Release/

      - name: Test
        run: python Script/test_screenshot.py
        shell: cmd

      - name: Release Runtime
        run: release_runtime.bat
        shell: cmd

      - name: Upload Runtime
        uses: actions/upload-artifact@v1
        with:
          name: EffekseerRuntime152e
          path: EffekseerRuntime150

      - name: Release Tool
        run: release_tool.bat
        shell: cmd

      - name: Upload Tool
        uses: actions/upload-artifact@v1
        with:
          name: Effekseer152eWin
          path: Effekseer150Win